import { describe, it, expect } from "vitest";
import fs from "node:fs";
import path from "node:path";
import { OG_IMAGE_SLUGS } from "@/config/ogImages";

// Every page used to share one 1024x1024 og-image.png while the runtime SEO
// component declared 1200x630. Cards are generated by
// scripts/generate-og-images.mjs (run after build:seo, then commit).

const ROOT = path.resolve(__dirname, "../../..");
const dir = path.join(ROOT, "public/og");

describe("per-page share cards", () => {
  it("has a card file for every slug in the generated list, and no strays", () => {
    const files = fs.readdirSync(dir).filter((f) => f.endsWith(".png")).map((f) => f.replace(/\.png$/, "")).sort();
    expect(files).toEqual([...OG_IMAGE_SLUGS].sort());
  });

  it("covers most prerendered routes", () => {
    const sitemap = fs.readFileSync(path.join(ROOT, "public/sitemap.xml"), "utf8");
    const routes = [...sitemap.matchAll(/<loc>https:\/\/www\.realtordesk\.ai([^<]*)<\/loc>/g)].map((m) => m[1] || "/");
    const covered = routes.filter((r) => OG_IMAGE_SLUGS.has(r === "/" ? "home" : r.replace(/^\/|\/$/g, "").replace(/\//g, "--")));
    // New pages fall back to /og-image.png until the generator is rerun; this
    // only fails when the set has drifted badly.
    expect(covered.length / routes.length).toBeGreaterThan(0.9);
  });

  it("are 1200x630 PNGs", () => {
    for (const f of fs.readdirSync(dir).filter((f) => f.endsWith(".png"))) {
      const b = fs.readFileSync(path.join(dir, f));
      expect(b.subarray(1, 4).toString(), f).toBe("PNG");
      expect([b.readUInt32BE(16), b.readUInt32BE(20)], f).toEqual([1200, 630]);
    }
  });

  it("are what the prerendered page declares", () => {
    const file = path.join(ROOT, "dist/pricing/index.html");
    if (!fs.existsSync(file) || !OG_IMAGE_SLUGS.has("pricing")) return; // needs build:seo
    const html = fs.readFileSync(file, "utf8");
    expect(html).toContain('property="og:image" content="https://www.realtordesk.ai/og/pricing.png"');
    expect(html).toContain('property="og:image:width" content="1200"');
    expect(html).toContain('name="twitter:image" content="https://www.realtordesk.ai/og/pricing.png"');
  });
});
