import { describe, it, expect } from "vitest";
import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";
import { RELATED_LABELS, RELATED_LINKS } from "@/config/relatedLinks";

// "Keep reading" links, generated by scripts/generate-related-links.mjs.
//
// The audit that prompted them found 45 of 87 indexed pages with one inbound
// link. These checks keep the system honest: the file must match its generator,
// every link must go somewhere real and public, and no page may be left linking
// to itself or to nothing.

const ROOT = path.resolve(__dirname, "../../..");
const APP = fs.readFileSync(path.join(ROOT, "src/App.tsx"), "utf8");
const declared = new Set([...APP.matchAll(/path="([^"]+)"/g)].map((m) => m[1]));
const gated = new Set(
  APP.split("\n")
    .filter((l) => /<ProtectedRoute|<RequireBilling/.test(l))
    .flatMap((l) => [...l.matchAll(/path="([^"]+)"/g)].map((m) => m[1])),
);
const sitemap = fs.readFileSync(path.join(ROOT, "public/sitemap.xml"), "utf8");
const indexed = new Set(
  [...sitemap.matchAll(/<loc>\s*([^<\s]+)\s*<\/loc>/g)].map(
    (m) => m[1].replace("https://www.realtordesk.ai", "") || "/",
  ),
);

describe("related links", () => {
  it("matches the generator that produces it", () => {
    // Editing a cluster without regenerating, or hand-editing the output, both
    // fail here. execFileSync throws on a non-zero exit.
    expect(() =>
      execFileSync("node", ["scripts/generate-related-links.mjs", "--check"], { cwd: ROOT, stdio: "pipe" }),
    ).not.toThrow();
  });

  it("only links between pages that exist and are indexed", () => {
    const bad: string[] = [];
    for (const [from, tos] of Object.entries(RELATED_LINKS)) {
      for (const p of [from, ...tos]) {
        if (!declared.has(p)) bad.push(`${p}: not a route in App.tsx`);
        if (gated.has(p)) bad.push(`${p}: behind <ProtectedRoute>`);
        if (!indexed.has(p)) bad.push(`${p}: not in sitemap.xml`);
      }
    }
    expect([...new Set(bad)].join("\n")).toBe("");
  });

  it("never links a page to itself, or twice to the same target", () => {
    const bad: string[] = [];
    for (const [from, tos] of Object.entries(RELATED_LINKS)) {
      if (tos.includes(from)) bad.push(`${from} links to itself`);
      if (new Set(tos).size !== tos.length) bad.push(`${from} repeats a target`);
    }
    expect(bad.join("\n")).toBe("");
  });

  it("gives every page between four and eight links", () => {
    const bad = Object.entries(RELATED_LINKS)
      .filter(([, tos]) => tos.length < 4 || tos.length > 8)
      .map(([from, tos]) => `${from}: ${tos.length} links`);
    expect(bad.join("\n")).toBe("");
  });

  it("describes every target with its own anchor text", () => {
    const missing = new Set<string>();
    for (const [from, tos] of Object.entries(RELATED_LINKS)) {
      for (const p of [from, ...tos]) if (!RELATED_LABELS[p]?.trim()) missing.add(p);
    }
    expect([...missing].join("\n")).toBe("");
  });

  it("keeps a standalone French page free of English link text", () => {
    // /fr/... routes have no entry, so no English list renders under French copy.
    expect(Object.keys(RELATED_LINKS).filter((k) => k.startsWith("/fr/"))).toEqual([]);
  });
});
