import { Link, useLocation } from "react-router-dom";
import { useTranslation } from "react-i18next";
import { RELATED_LABELS, RELATED_LINKS } from "@/config/relatedLinks";

// "Keep reading": a short list of related pages above the footer columns.
//
// The lists come from src/config/relatedLinks.ts, generated by
// scripts/generate-related-links.mjs. The prerenderer reads the same file, so the
// links crawlers see in the static HTML are the links visitors see here.
//
// It lives in the shared footer rather than in each page so that adding a page
// to a cluster in the generator is the only step needed to link it everywhere.
// A page with no entry renders nothing, which covers the homepage, the hubs and
// the utility pages that are linked from the header and footer already.
//
// The heading is static English on purpose: prerendering lifts plain text and
// skips elements holding an expression, and a standalone French route (/fr/...)
// has no entry at all, so no English list ever appears under French copy.

export function RelatedPages() {
  const { pathname } = useLocation();
  const { t } = useTranslation();
  const key = pathname.replace(/\/+$/, "") || "/";
  const targets = RELATED_LINKS[key];
  if (!targets?.length) return null;

  return (
    <nav
      aria-label={t("marketingFooter.keepReading", "Keep reading")}
      className="mx-auto max-w-[1200px] mb-12 pb-10 border-b border-rd-line"
    >
      <div className="text-[11px] font-bold uppercase tracking-[0.08em] text-rd-ink-900 mb-3.5">
        {t("marketingFooter.keepReading", "Keep reading")}
      </div>
      <ul className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-x-8 gap-y-1">
        {targets.map((to) => (
          <li key={to}>
            <Link
              to={to}
              className="text-[14px] text-rd-ink-700 hover:text-rd-ink-900 underline-offset-2 hover:underline inline-flex items-center min-h-[28px]"
            >
              {RELATED_LABELS[to] ?? to}
            </Link>
          </li>
        ))}
      </ul>
    </nav>
  );
}
