// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { authStorage } from '@/lib/auth/sessionPersistence';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // localStorage by default; sessionStorage when "Remember me" is cleared,
    // so an unremembered session dies with the tab. See sessionPersistence.ts.
    storage: authStorage,
    persistSession: true,
    autoRefreshToken: true,
    // The OAuth callback comes back with the code in the URL; let the client
    // complete the PKCE exchange and then strip it from the address bar.
    detectSessionInUrl: true,
    flowType: 'pkce',
  }
});